#!/usr/bin/env ruby

lib = File.expand_path('../../lib', __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require 'podcast_feed_gen/generator'

gen = PodcastFeedGen::Generator.new

rss = gen.gen!

print rss
